package aplicacion.modelo.dominio;
// Generated 20/06/2018 20:13:14 by Hibernate Tools 4.3.1



/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private Integer autCodigo;
     private String autApellidos;
     private String autNombres;

    public Autor() {
    }

    public Autor(String autApellidos, String autNombres) {
       this.autApellidos = autApellidos;
       this.autNombres = autNombres;
    }
   
    public Integer getAutCodigo() {
        return this.autCodigo;
    }
    
    public void setAutCodigo(Integer autCodigo) {
        this.autCodigo = autCodigo;
    }
    public String getAutApellidos() {
        return this.autApellidos;
    }
    
    public void setAutApellidos(String autApellidos) {
        this.autApellidos = autApellidos;
    }
    public String getAutNombres() {
        return this.autNombres;
    }
    
    public void setAutNombres(String autNombres) {
        this.autNombres = autNombres;
    }




}


