package aplicacion.modelo.dominio;
// Generated 24/06/2018 14:09:26 by Hibernate Tools 4.3.1



/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private Integer autCodigo;
     private String autApellidos;
     private String autNombres;

    public Autor() {
    }
    /**
     * 
     * @param autApellidos
     * @param autNombres 
     */
    public Autor(String autApellidos, String autNombres) {
       this.autApellidos = autApellidos;
       this.autNombres = autNombres;
    }
    /**
     * constructor de AutCodigo con su get
     * @return 
     */
    public Integer getAutCodigo() {
        return this.autCodigo;
    }
    /**
     * constructor de AutCodigo con su set
     * @param autCodigo 
     */
    public void setAutCodigo(Integer autCodigo) {
        this.autCodigo = autCodigo;
    }
    /**
     * constructor de AutApellidos con su get
     * @return 
     */
    public String getAutApellidos() {
        return this.autApellidos;
    }
    /**
     * constructor de AutApellidos con su set
     * @param autApellidos 
     */
    public void setAutApellidos(String autApellidos) {
        this.autApellidos = autApellidos;
    }
    /**
     * constructor de AutNombres con su get
     * @return 
     */
    public String getAutNombres() {
        return this.autNombres;
    }
    /**
     * constructor de AutNombres con su set
     * @param autNombres 
     */
    public void setAutNombres(String autNombres) {
        this.autNombres = autNombres;
    }




}


