package aplicacion.modelo.dominio;
// Generated 24/06/2018 14:09:26 by Hibernate Tools 4.3.1



/**
 * Clasificacion generated by hbm2java
 */
public class Clasificacion  implements java.io.Serializable {


     private Integer claCodigo;
     private int claIdentificador;
     private String claDescripcion;

    public Clasificacion() {
    }
    /**
     * 
     * @param claIdentificador
     * @param claDescripcion 
     */
    public Clasificacion(int claIdentificador, String claDescripcion) {
       this.claIdentificador = claIdentificador;
       this.claDescripcion = claDescripcion;
    }
    /**
     * constructor de ClaCodigo con su get
     * @return 
     */
    public Integer getClaCodigo() {
        return this.claCodigo;
    }
    /**
     * constructor de ClaCodigo con su set
     * @param claCodigo 
     */
    public void setClaCodigo(Integer claCodigo) {
        this.claCodigo = claCodigo;
    }
    /**
     * constructor de ClaIdentificado con su get
     * @return 
     */
    public int getClaIdentificador() {
        return this.claIdentificador;
    }
    /**
     * constructor de ClaIdentificador con su set
     * @param claIdentificador 
     */
    public void setClaIdentificador(int claIdentificador) {
        this.claIdentificador = claIdentificador;
    }
    /**
     * constructor de ClaDescripcion con su get
     * @return 
     */
    public String getClaDescripcion() {
        return this.claDescripcion;
    }
    /**
     * constructor de ClaDescripcion con su set
     * @param claDescripcion 
     */
    public void setClaDescripcion(String claDescripcion) {
        this.claDescripcion = claDescripcion;
    }




}


