package aplicacion.modelo.dominio;
// Generated 24/06/2018 14:09:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetallePrestamo generated by hbm2java
 */
public class DetallePrestamo  implements java.io.Serializable {


     private Integer dpCodigo;
     private boolean dpEstado;
     private Date dpFechaADevolver;
     private String dpTurno;
     private Date dpFechaDevolucion;
     private int dpPrestamo;
     private String dpPublicacion;

    public DetallePrestamo() {
    }

    public DetallePrestamo(boolean dpEstado, Date dpFechaADevolver, String dpTurno, Date dpFechaDevolucion, int dpPrestamo, String dpPublicacion) {
       this.dpEstado = dpEstado;
       this.dpFechaADevolver = dpFechaADevolver;
       this.dpTurno = dpTurno;
       this.dpFechaDevolucion = dpFechaDevolucion;
       this.dpPrestamo = dpPrestamo;
       this.dpPublicacion = dpPublicacion;
    }
    /**
     * constructor de DpCodigo con su get
     * @return 
     */
    public Integer getDpCodigo() {
        return this.dpCodigo;
    }
    /**
     * constructor de DpCodigo con su set
     * @param dpCodigo 
     */
    public void setDpCodigo(Integer dpCodigo) {
        this.dpCodigo = dpCodigo;
    }
    /**
     * constructor de isDpEstado 
     * @return 
     */
    public boolean isDpEstado() {
        return this.dpEstado;
    }
    /**
     * constructor de DpEstado con su set
     * @param dpEstado 
     */
    public void setDpEstado(boolean dpEstado) {
        this.dpEstado = dpEstado;
    }
    /**
     * constructor de DpFechaADevolver con su get
     * @return 
     */
    public Date getDpFechaADevolver() {
        return this.dpFechaADevolver;
    }
    /**
     * constructor de DpFechaADevolver con su set
     * @param dpFechaADevolver 
     */
    public void setDpFechaADevolver(Date dpFechaADevolver) {
        this.dpFechaADevolver = dpFechaADevolver;
    }
    /**
     * constructor de DpTurno con su get
     * @return 
     */
    public String getDpTurno() {
        return this.dpTurno;
    }
    /**
     * constructor de DpTurno con su set
     * @param dpTurno 
     */
    public void setDpTurno(String dpTurno) {
        this.dpTurno = dpTurno;
    }
    /**
     * constructor de DpFechaDevolucion con su get
     * @return 
     */
    public Date getDpFechaDevolucion() {
        return this.dpFechaDevolucion;
    }
    /**
     * constructor de DpFechaDevolucion con su set
     * @param dpFechaDevolucion 
     */
    public void setDpFechaDevolucion(Date dpFechaDevolucion) {
        this.dpFechaDevolucion = dpFechaDevolucion;
    }
    /**
     * constructor de DpPrestamo con su get
     * @return 
     */
    public int getDpPrestamo() {
        return this.dpPrestamo;
    }
    /**
     * constructor de DpPrestamo su set
     * @param dpPrestamo 
     */
    public void setDpPrestamo(int dpPrestamo) {
        this.dpPrestamo = dpPrestamo;
    }
    /**
     * constructor de DpPublicacion con su get
     * @return 
     */
    public String getDpPublicacion() {
        return this.dpPublicacion;
    }
    /**
     * constructor de DpPublicacion con su set
     * @param dpPublicacion 
     */
    public void setDpPublicacion(String dpPublicacion) {
        this.dpPublicacion = dpPublicacion;
    }




}


