package aplicacion.modelo.dominio;
// Generated 19/06/2018 01:06:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer perCodigo;
     private String perApellidos;
     private String perNombres;
     private String perDni;
     private Date perFechaNac;
     private String perEmail;
     private String perDireccion;
     private String perTelefono;
     private int perUsuario;

    public Perfil() {
    }

    public Perfil(String perApellidos, String perNombres, String perDni, Date perFechaNac, String perEmail, String perDireccion, String perTelefono, int perUsuario) {
       this.perApellidos = perApellidos;
       this.perNombres = perNombres;
       this.perDni = perDni;
       this.perFechaNac = perFechaNac;
       this.perEmail = perEmail;
       this.perDireccion = perDireccion;
       this.perTelefono = perTelefono;
       this.perUsuario = perUsuario;
    }
   
    public Integer getPerCodigo() {
        return this.perCodigo;
    }
    
    public void setPerCodigo(Integer perCodigo) {
        this.perCodigo = perCodigo;
    }
    public String getPerApellidos() {
        return this.perApellidos;
    }
    
    public void setPerApellidos(String perApellidos) {
        this.perApellidos = perApellidos;
    }
    public String getPerNombres() {
        return this.perNombres;
    }
    
    public void setPerNombres(String perNombres) {
        this.perNombres = perNombres;
    }
    public String getPerDni() {
        return this.perDni;
    }
    
    public void setPerDni(String perDni) {
        this.perDni = perDni;
    }
    public Date getPerFechaNac() {
        return this.perFechaNac;
    }
    
    public void setPerFechaNac(Date perFechaNac) {
        this.perFechaNac = perFechaNac;
    }
    public String getPerEmail() {
        return this.perEmail;
    }
    
    public void setPerEmail(String perEmail) {
        this.perEmail = perEmail;
    }
    public String getPerDireccion() {
        return this.perDireccion;
    }
    
    public void setPerDireccion(String perDireccion) {
        this.perDireccion = perDireccion;
    }
    public String getPerTelefono() {
        return this.perTelefono;
    }
    
    public void setPerTelefono(String perTelefono) {
        this.perTelefono = perTelefono;
    }
    public int getPerUsuario() {
        return this.perUsuario;
    }
    
    public void setPerUsuario(int perUsuario) {
        this.perUsuario = perUsuario;
    }




}


