package aplicacion.modelo.dominio;
// Generated 20/06/2018 20:13:14 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer preCodigo;
     private Date preFechaPrestamo;
     private boolean preEstado;
     private String preAdministrativo;
     private int preSocio;

    public Prestamo() {
    }

    public Prestamo(Date preFechaPrestamo, boolean preEstado, String preAdministrativo, int preSocio) {
       this.preFechaPrestamo = preFechaPrestamo;
       this.preEstado = preEstado;
       this.preAdministrativo = preAdministrativo;
       this.preSocio = preSocio;
    }
   
    public Integer getPreCodigo() {
        return this.preCodigo;
    }
    
    public void setPreCodigo(Integer preCodigo) {
        this.preCodigo = preCodigo;
    }
    public Date getPreFechaPrestamo() {
        return this.preFechaPrestamo;
    }
    
    public void setPreFechaPrestamo(Date preFechaPrestamo) {
        this.preFechaPrestamo = preFechaPrestamo;
    }
    public boolean isPreEstado() {
        return this.preEstado;
    }
    
    public void setPreEstado(boolean preEstado) {
        this.preEstado = preEstado;
    }
    public String getPreAdministrativo() {
        return this.preAdministrativo;
    }
    
    public void setPreAdministrativo(String preAdministrativo) {
        this.preAdministrativo = preAdministrativo;
    }
    public int getPreSocio() {
        return this.preSocio;
    }
    
    public void setPreSocio(int preSocio) {
        this.preSocio = preSocio;
    }




}


