package aplicacion.modelo.dominio;
// Generated 24/06/2018 14:09:26 by Hibernate Tools 4.3.1



/**
 * Publicacion generated by hbm2java
 */
public class Publicacion  implements java.io.Serializable {


     private String pubCodigo;
     private String pubNombre;
     private String pubResumen;
     private boolean pubEstado;
     private String pubTipo;
     private int pubStock;
     private int pubEditorial;

    public Publicacion() {
    }

	
    public Publicacion(String pubCodigo, String pubNombre, boolean pubEstado, String pubTipo, int pubStock, int pubEditorial) {
        this.pubCodigo = pubCodigo;
        this.pubNombre = pubNombre;
        this.pubEstado = pubEstado;
        this.pubTipo = pubTipo;
        this.pubStock = pubStock;
        this.pubEditorial = pubEditorial;
    }
    public Publicacion(String pubCodigo, String pubNombre, String pubResumen, boolean pubEstado, String pubTipo, int pubStock, int pubEditorial) {
       this.pubCodigo = pubCodigo;
       this.pubNombre = pubNombre;
       this.pubResumen = pubResumen;
       this.pubEstado = pubEstado;
       this.pubTipo = pubTipo;
       this.pubStock = pubStock;
       this.pubEditorial = pubEditorial;
    }
   
    public String getPubCodigo() {
        return this.pubCodigo;
    }
    
    public void setPubCodigo(String pubCodigo) {
        this.pubCodigo = pubCodigo;
    }
    public String getPubNombre() {
        return this.pubNombre;
    }
    
    public void setPubNombre(String pubNombre) {
        this.pubNombre = pubNombre;
    }
    public String getPubResumen() {
        return this.pubResumen;
    }
    
    public void setPubResumen(String pubResumen) {
        this.pubResumen = pubResumen;
    }
    public boolean isPubEstado() {
        return this.pubEstado;
    }
    
    public void setPubEstado(boolean pubEstado) {
        this.pubEstado = pubEstado;
    }
    public String getPubTipo() {
        return this.pubTipo;
    }
    
    public void setPubTipo(String pubTipo) {
        this.pubTipo = pubTipo;
    }
    public int getPubStock() {
        return this.pubStock;
    }
    
    public void setPubStock(int pubStock) {
        this.pubStock = pubStock;
    }
    public int getPubEditorial() {
        return this.pubEditorial;
    }
    
    public void setPubEditorial(int pubEditorial) {
        this.pubEditorial = pubEditorial;
    }




}


