package aplicacion.modelo.dominio;
// Generated 24/06/2018 14:09:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer revCodigo;
     private Date revFechaEmision;
     private Date revFechaTurno;
     private boolean revEstado;
     private int revPerfil;

    public Reserva() {
    }

    public Reserva(Date revFechaEmision, Date revFechaTurno, boolean revEstado, int revPerfil) {
       this.revFechaEmision = revFechaEmision;
       this.revFechaTurno = revFechaTurno;
       this.revEstado = revEstado;
       this.revPerfil = revPerfil;
    }
   
    public Integer getRevCodigo() {
        return this.revCodigo;
    }
    
    public void setRevCodigo(Integer revCodigo) {
        this.revCodigo = revCodigo;
    }
    public Date getRevFechaEmision() {
        return this.revFechaEmision;
    }
    
    public void setRevFechaEmision(Date revFechaEmision) {
        this.revFechaEmision = revFechaEmision;
    }
    public Date getRevFechaTurno() {
        return this.revFechaTurno;
    }
    
    public void setRevFechaTurno(Date revFechaTurno) {
        this.revFechaTurno = revFechaTurno;
    }
    public boolean isRevEstado() {
        return this.revEstado;
    }
    
    public void setRevEstado(boolean revEstado) {
        this.revEstado = revEstado;
    }
    public int getRevPerfil() {
        return this.revPerfil;
    }
    
    public void setRevPerfil(int revPerfil) {
        this.revPerfil = revPerfil;
    }




}


