package aplicacion.modelo.dominio;
// Generated 05/06/2018 00:58:07 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private String usuario;
     private String contrasena;
     private String email;
     private long dni;
     private int tipoUsuario; //1 usuarioAdmin 2 usuarioSupervisor 3 usuarioComún

    public Usuario() {
    }

	
    public Usuario(String nombre, String apellido, String usuario, String contrasena, long dni, int tipoUsuario) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.dni = dni;
        this.tipoUsuario = tipoUsuario;
    }
    public Usuario(String nombre, String apellido, String usuario, String contrasena, String email, long dni, int tipoUsuario) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.email = email;
       this.dni = dni;
       this.tipoUsuario = tipoUsuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public long getDni() {
        return this.dni;
    }
    
    public void setDni(long dni) {
        this.dni = dni;
    }
    public int getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(int tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }




}


